# This manifest is automatically generated by the Enrise DevBoxHelper
# https://github.com/Enrise/devbox

import "{SHORTNAME}-*.pp"

node default {
    notify {'Setting up devbox "{LONGNAME}"': }

    # Set default path for Exec calls
    Exec { path => '{MAN_EXECPATH}' }

    class {'{SHORTNAME}::packages': }
    ->
    {CLASSES}
    class {'{SHORTNAME}::finalize': }

}